import genanki

# List of Linux directories and their descriptions
linux_dirs = [
('du', 'nǐ', '你', '<img src="你.gif">', '', '', '', ''),
('Sie ', 'nín', '您', '<img src="您.gif">', '', '', '', ''),
('gut', 'hǎo', '好', '<img src="好.gif">', '', '', '', ''),
('Fragepartikel (ja/nein)', 'ma', '吗', '<img src="吗.gif">', '', '', '', ''),
('ich', 'wǒ', '我', '<img src="我.gif">', '', '', '', ''),
('sehr', 'hěn', '很', '<img src="很.gif">', '', '', '', ''),
('Fragepartikel (rückfragen)', 'ne', '呢', '<img src="呢.gif">', '', '', '', ''),
('es geht so ', 'mǎ mǎ hǔ hǔ', '马马虎虎', '<img src="马.gif">', '<img src="马.gif">', '<img src="虎.gif">', '<img src="虎.gif">', ''),
('Auf Wiedersehen ', 'zài jiàn', '再见', '<img src="再.gif">', '<img src="见.gif">', '', '', ''),
('beschäftigt, viel zu tun haben', 'máng', '忙', '<img src="忙.gif">', '', '', '', ''),
('erschöpft', 'lèi', '累', '<img src="累.gif">', '', '', '', ''),
('hungrig ', 'è', '饿', '<img src="饿.gif">', '', '', '', ''),
('durstig ', 'kě', '渴', '<img src="渴.gif">', '', '', '', ''),
('nicht; nein ', 'bù', '不', '<img src="不.gif">', '', '', '', ''),
('Lili', 'lǐ lì', '李莉', '<img src="李.gif">', '<img src="莉.gif">', '', '', ''),
('Johann', 'yuē hàn', '约翰', '<img src="约.gif">', '<img src="翰.gif">', '', '', ''),
('Entschuldigung, darf (ich) fragen', 'qǐng wèn', '请问', '<img src="请.gif">', '<img src="问.gif">', '', '', ''),
('heißen, rufen, nennen', 'jiào', '叫', '<img src="叫.gif">', '', '', '', ''),
('was, was für (ein)', 'shén me', '什么', '<img src="什.gif">', '<img src="么.gif">', '', '', ''),
('Name', 'míng zì', '名字', '<img src="名.gif">', '<img src="字.gif">', '', '', ''),
('heißen (mit Familienamen)', 'xìng', '姓', '<img src="姓.gif">', '', '', '', ''),
('teuer, wertvoll', 'guì', '贵', '<img src="贵.gif">', '', '', '', ''),
('sein', 'shì', '是', '<img src="是.gif">', '', '', '', ''),
('LehrerIn', 'lǎo shī', '老师', '<img src="老.gif">', '<img src="师.gif">', '', '', ''),
('IngenieurIn', 'gōng chéng shī', '工程师', '<img src="工.gif">', '<img src="程.gif">', '<img src="师.gif">', '', ''),
('sie (Singular)', 'tā', '她', '<img src="她.gif">', '', '', '', ''),
('Pluralendung für Personen', 'men', '们', '<img src="们.gif">', '', '', '', ''),
('ihr', 'nǐ men', '你们', '<img src="你.gif">', '<img src="们.gif">', '', '', ''),
('SekretärIn', 'mì shū', '秘书', '<img src="秘.gif">', '<img src="书.gif">', '', '', ''),
('SchülerIn', 'xué shēng', '学生', '<img src="学.gif">', '<img src="生.gif">', '', '', ''),
('vorstellen, empfehlen', 'jiè shào', '介绍', '<img src="介.gif">', '<img src="绍.gif">', '', '', ''),
('mal kurz', 'yī xià', '一下', '<img src="一.gif">', '<img src="下.gif">', '', '', ''),
('er ', 'tā', '他', '<img src="他.gif">', '', '', '', ''),
('Attributpartikel', 'de', '的', '<img src="的.gif">', '', '', '', ''),
('Freund', 'péng yǒu', '朋友', '<img src="朋.gif">', '<img src="友.gif">', '', '', ''),
('Wang Gang', 'wáng gāng', '王刚', '<img src="王.gif">', '<img src="刚.gif">', '', '', ''),
('Deng Xiaoming', 'dèng xiǎo míng', '邓小明', '<img src="邓.gif">', '<img src="小.gif">', '<img src="明.gif">', '', ''),
('kennen lernen, kennen', 'rèn shi', '认识', '<img src="认.gif">', '<img src="识.gif">', '', '', ''),
('sich freuen, freudig, froh', 'gāo xìng', '高兴', '<img src="高.gif">', '<img src="兴.gif">', '', '', ''),
('wir ', 'wǒ men', '我们', '<img src="我.gif">', '<img src="们.gif">', '', '', ''),
('auch ', 'yě', '也', '<img src="也.gif">', '', '', '', ''),
('Herr; Ehemann', 'xiān shēng', '先生', '<img src="先.gif">', '<img src="生.gif">', '', '', ''),
('dieser, diese, das ', 'zhè', '这', '<img src="这.gif">', '', '', '', ''),
('Visitenkarte', 'míng piàn', '名片', '<img src="名.gif">', '<img src="片.gif">', '', '', ''),
('Danke', 'xiè xie', '谢谢', '<img src="谢.gif">', '<img src="谢.gif">', '', '', ''),
('England', 'yīng guó', '英国', '<img src="英.gif">', '<img src="国.gif">', '', '', ''),
('und', 'hé', '和', '<img src="和.gif">', '', '', '', ''),
('Frankreich', 'fǎ guó', '法国', '<img src="法.gif">', '<img src="国.gif">', '', '', ''),
('jendes, das(dort)', 'nà', '那', '<img src="那.gif">', '', '', '', ''),
('Spanien', 'xī bān yá', '西班牙', '<img src="西.gif">', '<img src="班.gif">', '<img src="牙.gif">', '', ''),
('Italien', 'yì dà lì', '意大利', '<img src="意.gif">', '<img src="大.gif">', '<img src="利.gif">', '', ''),
('China', 'zhōng guó', '中国', '<img src="中.gif">', '<img src="国.gif">', '', '', ''),
('sich vefinden; in, bei, an, Auf', 'zài', '在', '<img src="在.gif">', '', '', '', ''),
('hier', 'zhè ér', '这儿', '<img src="这.gif">', '<img src="儿.gif">', '', '', ''),
('Deutschland', 'dé guó', '德国', '<img src="德.gif">', '<img src="国.gif">', '', '', ''),
('dort', 'nà ér', '那儿', '<img src="那.gif">', '<img src="儿.gif">', '', '', ''),
('USA', 'měi guó', '美国', '<img src="美.gif">', '<img src="国.gif">', '', '', ''),
('Japan', 'rì běn', '日本', '<img src="日.gif">', '<img src="本.gif">', '', '', ''),
('Österreich', 'nǎ ér', '哪儿', '<img src="哪.gif">', '<img src="儿.gif">', '', '', ''),
('Schweiz', 'ào dì lì', '奥地利', '<img src="奥.gif">', '<img src="地.gif">', '<img src="利.gif">', '', ''),
('wer', 'ruì shì', '瑞士', '<img src="瑞.gif">', '<img src="士.gif">', '', '', ''),
('MitschlülerIn, KommilitonIn', 'shuí', '谁', '<img src="谁.gif">', '', '', '', ''),
('welcher/s', 'tóng xué', '同学', '<img src="同.gif">', '<img src="学.gif">', '', '', ''),
('Land ', 'nǎ', '哪', '<img src="哪.gif">', '', '', '', ''),
('Mensch ', 'guó', '国', '<img src="国.gif">', '', '', '', ''),
('Deutsche/r ', 'rén', '人', '<img src="人.gif">', '', '', '', ''),
('können(durch Lernen und Übung)', 'dé guó rén', '德国人', '<img src="德.gif">', '<img src="国.gif">', '<img src="人.gif">', '', ''),
('sprechen', 'huì', '会', '<img src="会.gif">', '', '', '', ''),
('chinesische Sprache ', 'shuō', '说', '<img src="说.gif">', '', '', '', ''),
('ein bisschen ', 'hàn yǔ', '汉语', '<img src="汉.gif">', '<img src="语.gif">', '', '', ''),
('japanische Sprache ', 'yì diǎn ér', '一点儿', '<img src="一.gif">', '<img src="点.gif">', '<img src="儿.gif">', '', ''),
('aus (Präposition)', 'rì yǔ', '日语', '<img src="日.gif">', '<img src="语.gif">', '', '', ''),
('kommen ', 'cóng', '从', '<img src="从.gif">', '', '', '', ''),
('London ', 'lái', '来', '<img src="来.gif">', '', '', '', ''),
('Nich der Rede Wert!', 'lún dūn', '伦敦', '<img src="伦.gif">', '<img src="敦.gif">', '', '', ''),
('Peking ', 'nǎ lǐ', '哪里', '<img src="哪.gif">', '<img src="里.gif">', '', '', ''),
('Universität', 'běi jīng', '北京', '<img src="北.gif">', '<img src="京.gif">', '', '', ''),
('studieren, Studium lernen', 'dà xué', '大学', '<img src="大.gif">', '<img src="学.gif">', '', '', ''),
('Berlin', 'xué xí', '学习', '<img src="学.gif">', '<img src="习.gif">', '', '', ''),
('Shanghai', 'bó lín', '柏林', '<img src="柏.gif">', '<img src="林.gif">', '', '', ''),
('Frima VW', 'shàng hǎi', '上海', '<img src="上.gif">', '<img src="海.gif">', '', '', ''),
('Frima', 'dà zhòng gōng sī', '大众公司', '<img src="大.gif">', '<img src="众.gif">', '<img src="公.gif">', '<img src="司.gif">', ''),
('arbeiten, Arbeit', 'gōng zuò', '工作', '<img src="工.gif">', '<img src="作.gif">', '', '', ''),
('null', 'líng', '零', '<img src="零.gif">', '', '', '', ''),
('eins', 'yī', '一', '<img src="一.gif">', '', '', '', ''),
('zwei', 'èr', '二', '<img src="二.gif">', '', '', '', ''),
('drei', 'sān', '三', '<img src="三.gif">', '', '', '', ''),
('vier', 'sì', '四', '<img src="四.gif">', '', '', '', ''),
('fünf', 'wǔ', '五', '<img src="五.gif">', '', '', '', ''),
('sechs', 'liù', '六', '<img src="六.gif">', '', '', '', ''),
('sieben', 'qī', '七', '<img src="七.gif">', '', '', '', ''),
('acht', 'bā', '八', '<img src="八.gif">', '', '', '', ''),
('neun', 'jiǔ', '九', '<img src="九.gif">', '', '', '', ''),
('zehn', 'shí', '十', '<img src="十.gif">', '', '', '', ''),
('jetzt', 'xiàn zài', '现在', '<img src="现.gif">', '<img src="在.gif">', '', '', ''),
('wie viel (für zahlen unter 10)', 'jǐ', '几', '<img src="几.gif">', '', '', '', ''),
('Uhr (bei Uhrzeiten)', 'diǎn zhōng', '点钟', '<img src="点.gif">', '<img src="钟.gif">', '', '', ''),
('halb', 'bàn', '半', '<img src="半.gif">', '', '', '', ''),
('Entschuldigung', 'duì bù qǐ', '对不起', '<img src="对.gif">', '<img src="不.gif">', '<img src="起.gif">', '', ''),
('bitte, bitten, einladen', 'qǐng', '请', '<img src="请.gif">', '', '', '', ''),
('wieder, noch, dann', 'zài', '再', '<img src="再.gif">', '', '', '', ''),
('(Zahl)mal', 'biàn', '遍', '<img src="遍.gif">', '', '', '', ''),
('Mittag', 'zhōng wǔ', '中午', '<img src="中.gif">', '<img src="午.gif">', '', '', ''),
('Minute/Minute (für Uhrzeit/Zeitdauer)', 'fēn zhōng', '分钟', '<img src="分.gif">', '<img src="钟.gif">', '', '', ''),
('keine Ursache', 'bù kè qì', '不客气', '<img src="不.gif">', '<img src="客.gif">', '<img src="气.gif">', '', ''),
('haben, es gibt, besitzen', 'yǒu', '有', '<img src="有.gif">', '', '', '', ''),
('Sache, Angelegenheit', 'shì qíng', '事情', '<img src="事.gif">', '<img src="情.gif">', '', '', ''),
('heute', 'jīn tiān', '今天', '<img src="今.gif">', '<img src="天.gif">', '', '', ''),
('Nachmittag', 'xià wǔ', '下午', '<img src="下.gif">', '<img src="午.gif">', '', '', ''),
('Virtelstunde (für Uhrzeit/Zeitdauer)', 'kè zhǒng', '刻种', '<img src="刻.gif">', '<img src="种.gif">', '', '', ''),
('Café', 'kā fēi guǎn', '咖啡馆', '<img src="咖.gif">', '<img src="啡.gif">', '<img src="馆.gif">', '', ''),
('warten', 'děng', '等', '<img src="等.gif">', '', '', '', ''),
('mit, folgen', 'gēn', '跟', '<img src="跟.gif">', '', '', '', ''),
('verabreden, Verabredung', 'yuē huì', '约会', '<img src="约.gif">', '<img src="会.gif">', '', '', ''),
('eilig; sich Sorgen machen', 'zháo jí', '着急', '<img src="着.gif">', '<img src="急.gif">', '', '', ''),
('noch', 'hái', '还', '<img src="还.gif">', '', '', '', ''),
('Zeit(dauer)', 'shí jiān', '时间', '<img src="时.gif">', '<img src="间.gif">', '', '', ''),
('morgen', 'míng tiān', '明天', '<img src="明.gif">', '<img src="天.gif">', '', '', ''),
('Tag im Datum (Mündlich), Nummer, Größe', 'hào', '号', '<img src="号.gif">', '', '', '', ''),
('Woche', 'xīng qī', '星期', '<img src="星.gif">', '<img src="期.gif">', '', '', ''),
('Jahr ', 'nián', '年', '<img src="年.gif">', '', '', '', ''),
('Monat ', 'yuè', '月', '<img src="月.gif">', '', '', '', ''),
('Tag im Datum (Schrift)', 'rì', '日', '<img src="日.gif">', '', '', '', ''),
('wissen', 'zhī dào', '知道', '<img src="知.gif">', '<img src="道.gif">', '', '', ''),
('wollen, müssen', 'yào', '要', '<img src="要.gif">', '', '', '', ''),
('sehen, lesen, anschauen, besuchen', 'kàn', '看', '<img src="看.gif">', '', '', '', ''),
('Kalender', 'rì lì', '日历', '<img src="日.gif">', '<img src="历.gif">', '', '', ''),
('Abend', 'wǎn shàng', '晚上', '<img src="晚.gif">', '<img src="上.gif">', '', '', ''),
('zusammen', 'yì qǐ', '一起', '<img src="一.gif">', '<img src="起.gif">', '', '', ''),
('nach...gehen, hingehen', 'qù', '去', '<img src="去.gif">', '', '', '', ''),
('Film ', 'diàn yǐng', '电影', '<img src="电.gif">', '<img src="影.gif">', '', '', ''),
('wollen, möchten, vermissen, denken', 'xiǎng', '想', '<img src="想.gif">', '', '', '', ''),
('hübsch, schön', 'piào liàng', '漂亮', '<img src="漂.gif">', '<img src="亮.gif">', '', '', ''),
('Frau', 'nǚ rén', '女人', '<img src="女.gif">', '<img src="人.gif">', '', '', ''),
('aber ', 'dàn shì', '但是', '<img src="但.gif">', '<img src="是.gif">', '', '', ''),
('Vormittag', 'shàng wǔ', '上午', '<img src="上.gif">', '<img src="午.gif">', '', '', ''),
('nicht(haben)', 'méi yǒu', '没有', '<img src="没.gif">', '<img src="有.gif">', '', '', ''),
('keine Ursache, macht nichts', 'méi guān xì', '没关系', '<img src="没.gif">', '<img src="关.gif">', '<img src="系.gif">', '', ''),
('Partikel für Vermutungen, Einverständnis', 'ba', '吧', '<img src="吧.gif">', '', '', '', ''),
('RMB/CNY (chinesische Währung)', 'rén mín bì', '人民币', '<img src="人.gif">', '<img src="民.gif">', '<img src="币.gif">', '', ''),
('tausend', 'qiān', '千', '<img src="千.gif">', '', '', '', ''),
('hundert', 'bǎi', '百', '<img src="百.gif">', '', '', '', ''),
('Euro', 'ōu yuán', '欧元', '<img src="欧.gif">', '<img src="元.gif">', '', '', ''),
('ZEW für Geld', 'yuán/ kuài', '元/ 块', '<img src="元.gif">', '<img src="/.gif">', '<img src=" .gif">', '<img src="块.gif">', ''),
('ZEW für Geld', 'jiǎo/ máo', '角/ 毛', '<img src="角.gif">', '<img src="/.gif">', '<img src=" .gif">', '<img src="毛.gif">', ''),
('ZEW für Geld', 'fēn', '分', '<img src="分.gif">', '', '', '', ''),
('leer, frei ', 'kōng', '空', '<img src="空.gif">', '', '', '', ''),
('Zimmer', 'fáng jiān', '房间', '<img src="房.gif">', '<img src="间.gif">', '', '', ''),
('haben wollen, brauchen ', 'yào', '要', '<img src="要.gif">', '', '', '', ''),
('Einzel- ', 'dān', '单', '<img src="单.gif">', '', '', '', ''),
('Doppel-, ZEW für paarige Dinge ', 'shuāng', '双', '<img src="双.gif">', '', '', '', ''),
('oder (zur Bildung ovn Alternativfragen)', 'hái shì', '还是', '<img src="还.gif">', '<img src="是.gif">', '', '', ''),
('ZEW für Zimmer ', 'jiān', '间', '<img src="间.gif">', '', '', '', ''),
('wohnen ', 'zhù', '住', '<img src="住.gif">', '', '', '', ''),
('zwei (in Verbindung mit ZEW)', 'liǎng', '两', '<img src="两.gif">', '', '', '', ''),
('Tag ', 'tiān', '天', '<img src="天.gif">', '', '', '', ''),
('wie viel (bei Geld oder wenn Menge über 10 zu sein scheint)', 'duō shǎo', '多少', '<img src="多.gif">', '<img src="少.gif">', '', '', ''),
('Geld ', 'qián', '钱', '<img src="钱.gif">', '', '', '', ''),
('"Stück" (allgemeines ZEW)', 'gè', '个', '<img src="个.gif">', '', '', '', ''),
('so, so sehr', 'zhè me', '这么', '<img src="这.gif">', '<img src="么.gif">', '', '', ''),
('können ', 'néng', '能', '<img src="能.gif">', '', '', '', ''),
('billig', 'pián yí', '便宜', '<img src="便.gif">', '<img src="宜.gif">', '', '', ''),
('dürfen, können', 'kě yǐ', '可以', '<img src="可.gif">', '<img src="以.gif">', '', '', ''),
('über (einer bestimmten Menge)', 'yǐ shàng', '以上', '<img src="以.gif">', '<img src="上.gif">', '', '', ''),
('O.K., in Ordnung, das geht ', 'xíng', '行', '<img src="行.gif">', '', '', '', ''),
('ausfüllen', 'tián', '填', '<img src="填.gif">', '', '', '', ''),
('Formular', 'biǎo gé', '表格', '<img src="表.gif">', '<img src="格.gif">', '', '', ''),
('Karte (Kredit-,Zugangskarte uä)', 'kǎ', '卡', '<img src="卡.gif">', '', '', '', ''),
('Gebäude, ZEW für Etage', 'lóu', '楼', '<img src="楼.gif">', '', '', '', ''),
('bezahlen', 'fù qián', '付钱', '<img src="付.gif">', '<img src="钱.gif">', '', '', ''),
('Partikel ', 'le', '了', '<img src="了.gif">', '', '', '', ''),
('insgesamt', 'yī gòng', '一共', '<img src="一.gif">', '<img src="共.gif">', '', '', ''),
('mit; benutzen, gebrauchen', 'yòng', '用', '<img src="用.gif">', '', '', '', ''),
('Hotel', 'bīn guǎn', '宾馆', '<img src="宾.gif">', '<img src="馆.gif">', '', '', ''),
('mit Karte bezahlen', 'shuā kǎ', '刷卡', '<img src="刷.gif">', '<img src="卡.gif">', '', '', ''),
('wechseln', 'huàn', '换', '<img src="换.gif">', '', '', '', ''),
('in der Nähe, direkte Umgebung', 'fù jìn', '附近', '<img src="附.gif">', '<img src="近.gif">', '', '', ''),
('Bank', 'yín háng', '银行', '<img src="银.gif">', '<img src="行.gif">', '', '', ''),
('gegenüber; gegenüberliegende Seite', 'duì miàn', '对面', '<img src="对.gif">', '<img src="面.gif">', '', '', ''),
('Geldautomat', 'zì dòng qǔ kuǎn jī', '自动取款机', '<img src="自.gif">', '<img src="动.gif">', '<img src="取.gif">', '<img src="款.gif">', '<img src="机.gif">'),
('holen, abholen', 'qǔ ', '取', '<img src="取.gif">', '', '', '', '')
]

# Define Anki note model
model_id = 1607392319
model = genanki.Model(
    model_id,
    'Simple Model',
    fields=[
        {'name': 'Wort'},
        {'name': 'Pinying'},
        {'name': 'Character'},
        {'name': 'MyMedia0'},
        {'name': 'MyMedia1'},
        {'name': 'MyMedia2'},
        {'name': 'MyMedia3'},
        {'name': 'MyMedia4'}
    ],
    templates=[
        {
            'name': 'Card 1',
            'qfmt': '{{Wort}}',
            'afmt': '<center><br>{{Pinying}}\n{{Character}}</br><br>{{MyMedia0}}</br><br>{{MyMedia1}}</br><br>{{MyMedia2}}</br><br>{{MyMedia3}}</br><br>{{MyMedia4}}</br></center>',
            'back':'abc'
        },
    ])

# Generate Anki cards and add them to a deck
deck_id = 2059400110
deck = genanki.Deck(deck_id, 'Lóng Neu')

for dir_name, description,de2, imgs1, imgs2, imgs3, imgs4, imgs5 in linux_dirs:
    note = genanki.Note(model=model, fields=[dir_name, description, de2,  imgs1, imgs2, imgs3, imgs4, imgs5])
    deck.add_note(note)

# Save the deck to an Anki package (*.apkg) file
package = genanki.Package(deck)
package.media_files = ['images/刷.gif','images/钱.gif','images/刻.gif','images/看.gif','images/一.gif','images/以.gif','images/师.gif','images/不.gif','images/亮.gif','images/附.gif','images/没.gif','images/去.gif','images/德.gif','images/见.gif','images/明.gif','images/奥.gif','images/众.gif','images/种.gif','images/利.gif','images/和.gif','images/晚.gif','images/问.gif','images/英.gif','images/名.gif','images/朋.gif','images/啡.gif','images/士.gif','images/取.gif','images/近.gif','images/日.gif','images/国.gif','images/住.gif','images/里.gif','images/还.gif','images/影.gif','images/林.gif','images/京.gif','images/地.gif','images/工.gif','images/遍.gif','images/会.gif','images/咖.gif','images/知.gif','images/从.gif','images/零.gif','images/王.gif','images/伦.gif','images/西.gif','images/学.gif','images/们.gif','images/下.gif','images/款.gif','images/瑞.gif','images/百.gif','images/生.gif','images/月.gif','images/共.gif','images/人.gif','images/欧.gif','images/呢.gif','images/秘.gif','images/在.gif','images/的.gif','images/但.gif','images/自.gif','images/宜.gif','images/刚.gif','images/邓.gif','images/海.gif','images/这.gif','images/有.gif','images/那.gif','images/李.gif','images/程.gif','images/房.gif','images/姓.gif','images/谁.gif','images/用.gif','images/起.gif','images/表.gif','images/好.gif','images/卡.gif','images/道.gif','images/老.gif','images/对.gif','images/她.gif','images/作.gif','images/同.gif','images/要.gif','images/六.gif','images/付.gif','images/楼.gif','images/民.gif','images/宾.gif','images/敦.gif','images/星.gif','images/先.gif','images/八.gif','images/小.gif','images/个.gif','images/跟.gif','images/么.gif','images/事.gif','images/公.gif','images/面.gif','images/九.gif','images/单.gif','images/填.gif','images/班.gif','images/请.gif','images/银.gif','images/元.gif','images/分.gif','images/几.gif','images/着.gif','images/我.gif','images/饿.gif','images/二.gif','images/汉.gif','images/半.gif','images/想.gif','images/等.gif','images/多.gif','images/识.gif','images/司.gif','images/北.gif','images/意.gif','images/电.gif','images/漂.gif','images/气.gif','images/兴.gif','images/号.gif','images/角.gif','images/马.gif','images/忙.gif','images/两.gif','images/书.gif','images/他.gif','images/本.gif','images/系.gif','images/莉.gif','images/年.gif','images/毛.gif','images/能.gif','images/柏.gif','images/再.gif','images/钟.gif','images/美.gif','images/了.gif','images/块.gif','images/五.gif','images/字.gif','images/馆.gif','images/虎.gif','images/渴.gif','images/习.gif','images/说.gif','images/换.gif','images/机.gif','images/币.gif','images/急.gif','images/高.gif','images/今.gif','images/认.gif','images/空.gif','images/情.gif','images/四.gif','images/吗.gif','images/三.gif','images/片.gif','images/便.gif','images/也.gif','images/期.gif','images/双.gif','images/天.gif','images/十.gif','images/介.gif','images/点.gif','images/千.gif','images/贵.gif','images/你.gif','images/吧.gif','images/七.gif','images/时.gif','images/累.gif','images/翰.gif','images/法.gif','images/格.gif','images/很.gif','images/来.gif','images/间.gif','images/动.gif','images/友.gif','images/语.gif','images/午.gif','images/约.gif','images/可.gif','images/您.gif','images/少.gif','images/现.gif','images/客.gif','images/历.gif','images/上.gif','images/哪.gif','images/谢.gif','images/是.gif','images/叫.gif','images/行.gif','images/大.gif','images/女.gif','images/关.gif','images/儿.gif','images/绍.gif','images/牙.gif','images/什.gif','images/中.gif']
package.write_to_file('long.apkg')

